# Generated by Django 6.1 on 2026-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20, unique=True)),
                ('ventes', models.IntegerField()),
                ('visiteurs', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('categorie', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
